disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - weak_delegate
 - line_length
 - force_cast
 - private_outlet
 - cyclomatic_complexity
 - type_body_length
 - file_length
 - for_where
 - identifier_name
 - function_body_length
 - redundant_string_enum_value
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - BISTests/
 - BISUITests/
